name: Build and Test on Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install Pthread and other dependencies
      shell: pwsh
      run: |
        # This step will attempt to install necessary packages.
        $pthreadPath = "C:\path\to\pthread\include"
        if (-Not (Test-Path $pthreadPath)) {
            Write-Host "Pthread not found. Please ensure it is installed or configure the project to use Windows threads."
            # You can include installation commands here if necessary, or remove the check if not required.
        } else {
            Write-Host "Pthread found."
        }

    - name: Download and Setup Mesa3D for OpenGL support
      run: |
        echo "Downloading Mesa3D for software OpenGL support..."
        curl -L -o mesa3d.zip https://github.com/pal1000/mesa-dist-win/releases/download/22.3.5/mesa3d-22.3.5-release-mingw.7z
        7z x mesa3d.zip -omesa3d
        echo "Setting OpenGL version overrides..."
        set MESA_GL_VERSION_OVERRIDE=4.5
        set MESA_GLSL_VERSION_OVERRIDE=450

    - name: Configure project with CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

    - name: Build project
      run: cmake --build build --config Release

    - name: Run the application using Mesa3D (OpenGL software renderer)
      run: |
        echo "Updating PATH to include Mesa3D..."
        set PATH=%PATH%;$(pwd)/mesa3d/x64/
        echo "Running the application..."
        .\build\Release\Master_TechDemo.exe
