name: Build and Test on Linux

on:
  push:
    branches:
      - '**'  # Monitor all branches
  pull_request:
    branches:
      - '**'  # Monitor all branches for PRs

jobs:
  build:
    runs-on: ubuntu-latest  # Switch to the latest Ubuntu environment

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++ mesa-utils libgl1-mesa-dev libglx-mesa0 libglvnd-dev xorg-dev  # Install Mesa3D and OpenGL libraries
        sudo apt-get install -y libpthread-stubs0-dev  # Install pthread

    - name: Configure project with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run the application using Mesa3D (software OpenGL)
      run: |
        export LIBGL_ALWAYS_SOFTWARE=1  # Use Mesa3D for software rendering
        ./build/Master_TechDemo
