name: Build and Test on Linux

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        echo "Installing necessary packages..."
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgl1-mesa-dev libglu1-mesa-dev libglfw3-dev

    - name: Configure project with CMake
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CMAKE_LIST_FILE="CMakeLists_linux.txt"

    - name: Build project
      run: cmake --build build --config Release

    - name: Run the application
      run: |
        echo "Running the application..."
        ./build/Master_TechDemo
